[mcp_servers.notion-project]
command = "npx"
args = ["-y", "@notionhq/notion-mcp-server"]
enabled = true
env_vars = ["NOTION_TOKEN"]

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
enabled = true

[mcp_servers.gitlab]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-gitlab"]
enabled = true
env_vars = ["GITLAB_API_URL", "GITLAB_PERSONAL_ACCESS_TOKEN"]

[mcp_servers.gitlab.tools.get_file_contents]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-post-search]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-update-page-markdown]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-update-a-block]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-delete-a-block]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-patch-block-children]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-patch-page]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-post-page]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-query-data-source]
approval_mode = "approve"

[mcp_servers.notion-project.tools.API-create-a-comment]
approval_mode = "approve"
